name: Cypress Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: 🎭 Install Cypress browsers
        run: npx cypress install

      - name: Create reports directory
        run: mkdir -p cypress/reports/html

      - name: 🧪 Run Cypress tests
        run: npx cypress run --reporter cypress-mochawesome-reporter

      - name: 📊 Upload Test Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-report
          path: cypress/reports/html
